version: 2
project_name: courier
builds:
  - id: courier
    main: .
    binary: courier
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
      - "-X github.com/theopenlane/courier/constants.CLIVersion={{ .Env.VERSION }}"
notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - courier

      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{ .Env.MACOS_SIGN_PASSWORD }}"

      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"
        wait: true
        timeout: 60m
archives:
  - formats: ['tar.gz'] # we can use binary, but it seems there's an issue where goreleaser skips the sboms
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
source:
  enabled: true
changelog:
  sort: asc
  use: github
sboms:
  - artifacts: archive
release:
  prerelease: auto
  github:
    owner: theopenlane
    name: courier
# This section defines how and which artifacts we want to sign for the release.
signs:
  - cmd: cosign
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign >= 2.0.0
    artifacts: archive
    output: true
    signature: "${artifact}.sigstore.json"
homebrew_casks:
  - homepage: 'https://github.com/theopenlane/courier'
    description: 'courier syncs Openlane organization controls and policies with a git repository'
    license: 'Apache-2.0'
    commit_author:
      name: theopenlane-bender
      email: bender@theopenlane.io
    repository:
      owner: theopenlane
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
